name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: bluefunda/release-foundry/.github/workflows/go-ci.yml@main
    with:
      build-command: "go build -o /dev/null ./cmd/abaper"
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
